- name: tauri-action
  # You may pin to the exact commit or the version.
  # uses: loloof64/tauri-action@639795e2ce6324ac70f68fe208f9f04f6121ee49
  uses: loloof64/tauri-action@marketplace_2
  with:
    # Github action for Tauri
    releaseId: # optional
    # The tag name of the release to create
    tagName: # optional
    # The name of the release to create
    releaseName: # optional
    # The body of the release to create
    releaseBody: # optional
    # Whether the release to create is a draft or not
    releaseDraft: # optional
    # Whether the release to create is a prerelease or not
    prerelease: # optional
    # Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: SHA of current commit
    releaseCommitish: # optional
    # path to the root of the project that will be built
    projectPath: # optional, default is .
    # path to the tauri.conf.json file if you want a configuration different from the default one
    configPath: # optional, default is tauri.conf.json
    # path to the distributable folder with your index.html and JS/CSS
    distPath: # optional
    # path to the PNG icon to use as app icon, relative to the projectPath
    iconPath: # optional
    # whether to include a debug build or not
    includeDebug: # optional
    # the package.json script to run to build the Tauri app
    npmScript: # optional
    # set this to true to use a globally installed tauri instead
    preferGlobal: # optional